from pwn import *
import re
import urllib.parse
import base64
import codecs

if __name__ == "__main__":
    io = remote('pwn-2021.duc.tf',31905)
    io.recvuntil(b'Press enter when you are ready to start your 30 seconds timer for the quiz...')
    io.sendline(b' ')
    io.recvline()
    line=io.recvline()
    print(line)
    io.sendline(b'2')
    io.recvline()
    io.recvline()
    line=io.recvline()
    print(line)
    line=line.decode('utf-8')
    num=str(int(line[-5:-1],16)).encode('utf-8')
    io.sendline(num)
    io.recvline()
    io.recvline()
    line=io.recvline()
    print(line)
    line=line.decode('utf-8')
    ch=chr(int('0x'+line[-3:-1],16)).encode('utf-8')
    io.sendline(ch)
    io.recvline()
    io.recvline()
    line=io.recvline()
    print(line)
    line=line.decode('utf-8')
    ch=urllib.parse.unquote_plus(line[74:-1])
    io.sendline(ch)
    io.recvline()
    io.recvline()
    line=io.recvline()
    print(line)
    line=line.decode('utf-8')
    b=line[56:-1]
    b=base64.b64decode(b)
    io.sendline(b)
    io.recvline()
    io.recvline()
    line=io.recvline()
    print(line)
    line=line.decode('utf-8')
    b=line[56:-1]
    b=base64.b64encode(b.encode('utf-8'))
    io.sendline(b)
    io.recvline()
    io.recvline()
    line=io.recvline()
    print(line)
    line=line.decode('utf-8')
    s=line[55:-1]
    s=codecs.encode(s, 'rot_13')
    io.sendline(s)
    io.recvline()
    io.recvline()
    line=io.recvline()
    print(line)
    line=line.decode('utf-8')
    s=line[66:-1]
    s=codecs.decode(s, 'rot_13')
    io.sendline(s)
    io.recvline()
    io.recvline()
    line=io.recvline()
    print(line)
    line=line.decode('utf-8')
    num=str(int(line[72:-1],2))
    io.sendline(num)
    io.recvline()
    io.recvline()
    line=io.recvline()
    print(line)
    line=line.decode('utf-8')
    num=str(bin(int(line[57:-1])))
    io.sendline(num)
    io.recvline()
    io.recvline()
    io.recvline()
    io.sendline('DUCTF')
    io.interactive()