version: "3.3"
services:
  chall:
    build:
      context: ./chall
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 128M
    networks:
      - securestorage
    ports:
      - '3999:3999'
      - '4000:4000'
    environment:
      - DEFAULT_SITE=http://localhost:3999
      - SANDBOX_SITE=http://localhost:4000
      - XSSBOT_SECRET=NOT_REMOTE_SECRET

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 128M
    networks:
      - securestorage
    environment:
      - SANDBOX_SITE=http://localhost:4000
      - FLAG=NOPE
      - XSSBOT_SECRET=NOT_REMOTE_SECRET

networks:
  securestorage: {}
