version: '3'

services:
  mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: django
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:latest
  
  web:
    build:
      context: .
      dockerfile: ./dreamsign/Dockerfile
    container_name: dreamsign
    depends_on:
      - mysql
      - redis
    links:
      - redis
      - mysql
    ports:
      - "8000:8000"
