version: "3.3"
services:
  chall:
    build:
      context: ./chall
      dockerfile: Dockerfile
    networks:
      - fbg
    ports:
      - '8000:5000'
    environment:
      - SITE=https://fbg.rars.win/
      - XSSBOT_SECRET=Wts6uFeMYZMnxBdz+U902DnBRjx8MmvgqCxYhuQmxJ8=

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    networks:
      - fbg
    environment:
      - SITE=https://fbg.rars.win/
      - FLAG=NOPE
      - XSSBOT_SECRET=Wts6uFeMYZMnxBdz+U902DnBRjx8MmvgqCxYhuQmxJ8=

networks:
  fbg: {}
