[global]
keep_alive = 5
workers = 8
secret_key = "eZ8J/CJ2LuGx/lI481zxWK/3BnIy+LYjhwSZnKkdrRY="
port = 4242

[global.databases]
pg_diesel = { url = "postgres://diesel:diesel@postgres:5432/diesel", pool_size = 1024 }

